## CHANGE this to the name of your plugin.
name: WeaponsPlus

## CHANGE this to your username.
author: Skw972

## CHANGE this to a meaninful but short description of your plugin.
description: Adds new fantastic weapons.

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.CHANGEME.slimefunaddon.ExampleAddon

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/Skw972/WeaponsPlus

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun
